action: https://defendtheweb.net/auth
pass_user: pass_user.csv
params_list: params.json
req_body:
  token: a511d833132fa2626d32a5e0fc977bc885f73732b6f840e0f41bc260d5ce1d80
  username: m7mdassia
  password: astmamsh123
headers:
  accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
  accept-encoding: gzip, deflate, br
  accept-language: en-US,en;q=0.9,ar;q=0.8,he;q=0.7
  cache-control: max-age=0
  content-length: 110
  content-type: application/x-www-form-urlencoded
  cookie: cookies_dismissed=1; auth_remember=bafddff1ef613a0b786291c9461f66389286c78047bb73df1af9fb9a4a35b1ae; PHPSESSID=vg3kmlrke70f6s62t055640f2h
  origin: https://defendtheweb.net
  referer: https://defendtheweb.net/auth
  sec-fetch-dest: document
  sec-fetch-mode: navigate
  sec-fetch-site: same-origin
  sec-fetch-user: ?1
  upgrade-insecure-requests: 1
  user-agent: Mozilla/5.0 (Linux; Android 8.0.0; SM-G955U Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Mobile Safari/537.36 Edg/101.0.4951.64