pass_user: pass_user.csv

Technologies: [
  "WordPress", "CMS Hub", "Drupal", "Joomla", "Shopify", "Prestashop", "Magento", "Webflow", "Concrete5", "TYPO3", "Ghost","Squarespace", "Wix", "Weebly", "Jimdo", "IONOS", "WebNode", "Mozello", "Site123", "Tumblr", "Medium", "Blogger", 
]

params_list: 
  password_param: [
      "password"
  ]
  user_param: [
      "username", "email", "log", "id"
  ]
  # these strings are used in a scoring system in order to locate the login button in the form 
  # the more you add here the more accurate the score.
  ButtonList: [
      "login", "signin", "submit"
  ]
  # checks if these strings are found in a form, this is used in the scoring function. 
  # the more you add here the more accurate the score.
  loginTexts: [
    'log-in', 'sign-in', 'log in',"login", "sign in"   
  ]