pass_user: pass_user.csv # Usernames and passwords list path

paramsList: 
  passwordParam: [
      "password"
  ]
  userParam: [
      "username", "email", "log", "id"
  ]
  # these strings are used in a scoring system in order to locate the login button in the form 
  # the more you add here the more accurate the score.
  ButtonList: [
      "login", "signin", "submit"
  ]
  # checks if these strings are found in a form, this is used in the scoring function. 
  # the more you add here the more accurate the score.
  loginTexts: [
    'log-in', 'sign-in', 'log in',"login", "sign in"   
  ]

Technologies: {
  "WordPress": "/wp-login.php", "CMS Hub": "", "Drupal": "?q=user/login", "/administrator": "", 
  "Prestashop": "/admin", "Magento": "/magento/admin", "Webflow": "", "Concrete5": "", "TYPO3": "",
   "Ghost": "", "Squarespace": "", "Wix": "", "Weebly": "", "Jimdo": "", "IONOS": "",
    "WebNode": "", "Mozello": "", "Site123": "", "Tumblr": "", "Medium": "", "Blogger": "", 
}
