url: https://demo.owasp-juice.shop/#/login
user_list:  user_list.txt
pass_list: pass_list.txt
user_param: email
pass_param: password
method: post
post_url: https://demo.owasp-juice.shop/rest/user/login
req_body: {"email":"mohamad@gmail.com","password":"astmamsh123"}
req_header:
  Host: demo.owasp-juice.shop
  User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0
  Accept: application/json, text/plain, */*
  Accept-Language: en-GB,en;q=0.5
  Accept-Encoding: gzip, deflate, br
  Content-Type: application/json
  Content-Length: 54
  Origin: https://demo.owasp-juice.shop
  Connection: keep-alive
  Referer: https://demo.owasp-juice.shop/
  Cookie: language=en; cookieconsent_status=dismiss
  Sec-Fetch-Dest: empty
  Sec-Fetch-Mode: cors
  Sec-Fetch-Site: same-origin
  TE: trailers
