url: https://brokencrystals.com/userlogin
req_body:
  csrf: "MWwcSalAUlvXeL2TRmEO0TM3DOvyhaWb"
  op: "csrf"
  password: "astmamsh123jgjh"
  user: "mohamadassi173@gmail.com"
headers:
  Host: defendtheweb.net
  User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0
  Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
  Accept-Language: en-GB,en;q=0.5
  Accept-Encoding: gzip, deflate, br
  Referer: https://defendtheweb.net/auth
  Content-Type: application/x-www-form-urlencoded
  Content-Length: 109
  Origin: https://defendtheweb.net
  Connection: keep-alive
  Cookie: auth_remember=a618176a078d576fe7e5f1a8c3b42d80f90de90c3c19af39f063ef0b1c9079a9; cookies_dismissed=1; PHPSESSID=cccd5b5d680h6qgterjt8gv2ta
  Upgrade-Insecure-Requests: 1
  Sec-Fetch-Dest: document
  Sec-Fetch-Mode: navigate
  Sec-Fetch-Site: same-origin
  Sec-Fetch-User: ?1
  TE: trailers