url: https://alqlambara.com/wp-login.php
pass_user: pass_user.csv
params_list: 
  password_param: [
      "password"
  ]
  user_param: [
      "username", "email", "log", "id"
  ]
  ButtonList: [
      "login", "sign in"
  ]
